---
openapi: 3.0.1
info:
  title: BlogApp API
  version: v1
paths:
  "/api/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Return a post list from an user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    author_id:
                      type: integer
                    title:
                      type: string
                    text:
                      type: string
                    comments_counter:
                      type: integer
                    likes_counter:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - author_id
                  - title
                  - text
                  - comments_counter
                  - likes_counter
                  - created_at
                  - updated_at
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    - name: post_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Return a comments list from a post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    author_id:
                      type: integer
                    text:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - author_id
                  - text
                  - created_at
                  - updated_at
    post:
      summary: Create a comment on a post
      tags:
      - Comment
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Comment created
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
